//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ОбщийОтдел
{
    using System;
    using System.Collections.Generic;
    
    public partial class Личное_посещение
    {
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public string Назначение { get; set; }
        public int Код_пользователя { get; set; }
        public Nullable<int> Код_пропуска { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
        public virtual Пропуск Пропуск { get; set; }
    }
}
