//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ХРАНИТЕЛЬ_ПРО
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заявка_на_посещение
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заявка_на_посещение()
        {
            this.Пропуск = new HashSet<Пропуск>();
        }
    
        public int Код_заявки { get; set; }
        public System.DateTime Начало_срока_действия { get; set; }
        public System.DateTime Конец_срока_действия { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Пропуск> Пропуск { get; set; }
        public virtual Статус_заявки Статус_заявки { get; set; }
    }
}
