//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ХРАНИТЕЛЬ_ПРО
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Хранитель_ПРО_КротоваEntities : DbContext
    {
        public Хранитель_ПРО_КротоваEntities()
            : base("name=Хранитель_ПРО_КротоваEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Групповое_посещение> Групповое_посещение { get; set; }
        public virtual DbSet<Группы_посещения> Группы_посещения { get; set; }
        public virtual DbSet<Заявка_на_посещение> Заявка_на_посещение { get; set; }
        public virtual DbSet<Личное_посещение> Личное_посещение { get; set; }
        public virtual DbSet<Отдел> Отдел { get; set; }
        public virtual DbSet<Подразделение> Подразделение { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
        public virtual DbSet<Пропуск> Пропуск { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
        public virtual DbSet<Статус_заявки> Статус_заявки { get; set; }
    }
}
