//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ХРАНИТЕЛЬ_ПРО
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пропуск
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Пропуск()
        {
            this.Групповое_посещение = new HashSet<Групповое_посещение>();
            this.Личное_посещение = new HashSet<Личное_посещение>();
        }
    
        public int Код_пропуска { get; set; }
        public int Код_заявки { get; set; }
        public string Цель_посещения { get; set; }
        public Nullable<int> Принимающий_сотрудник { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Групповое_посещение> Групповое_посещение { get; set; }
        public virtual Заявка_на_посещение Заявка_на_посещение { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Личное_посещение> Личное_посещение { get; set; }
    }
}
